version: '3.8'
services:

  postgresql:
    image: postgres:14.7-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: creator
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: toy_bank
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_USER: user
    ports:
      - "5672:5672"
      - "15672:15672"

  client-backend:
    image: bank-0.0.1
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql/toy_bank
      SPRING_DATASOURCE_USERNAME: creator
      SPRING_DATASOURCE_PASSWORD: 1111
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: pass
      SPRING_RABBITMQ_HOST: rabbitmq