version: '3.8'
services:
  client-backend:
    image: bank-0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
      - rabbitmq
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/toy_bank

  rabbitmq:
      image: rabbitmq:3-management-alpine
      environment:
        - RABBITMQ_DEFAULT_PASS=localhost
        - RABBITMQ_DEFAULT_PASS=pass
        - RABBITMQ_DEFAULT_USER=user
      ports:
        - "5672:5672"
        - "15672:15672"

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: creator
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    restart: unless-stopped

